#pragma once

namespace UI_OBJECT
{
	enum START_ID{TITLE,TEXT,BUTTON,END};
	enum GAME_ID{BACKGROUND, BOSSBACKGROUND ,PLAYERHEAD ,HP,MP, BOSSHP, GAME_UI_END};
}
namespace GAMEOBJECT
{
	enum UPDATE_ID{PLAYER,MONSTER, MONSTER_ARMOR , BOSS, BOSSSKIL  ,NPC, Prob ,UPDATE_END};
	enum UPDATE_SKIL { NORMAL, DASH, MAGIC, FINAL,SKIL_END };
}
enum EOPTION { NORMAL, WALL, FALL, CREATEWALL };
enum EMONSTER { ARCHER, ZOMBIE, PLANT, EARTHBOSS, MAGIC };